### PR TITLE
Move almost all configurations from the plugin into the task

### LINKED ISSUE #108: Move conventions of the task inputs to the tasks
**Is your feature request related to a problem? Please describe.**
https://github.com/AlecStrong/Grammar-Kit-Composer uses the tasks of this plugin. Updating to the latest version fails because the conventions inputs are not set, only the required inputs.
At the moment you need to apply this plugin to get the conventions of the required task's input. Instead, you should move the conventions into the tasks to only reuse the tasks.

**Describe the solution you'd like**
Move almost all logic to the task to prevent applying the plugin or copying the conventions.

**Describe alternatives you've considered**
Copying the convention task inputs

**Additional context**

### PR DESCRIPTION
**Pull request by hfhbd**
# Pull Request Details

Moved almost all task input logic to the task to reuse this logic when only using the tasks without the plugin

## Description

It is currently impossible to reuse the task only without copying the conventions.

## Related Issue
Fixes #108

## Motivation and Context

See #108

## How Has This Been Tested
Existing tests don't fail

## Types of changes
- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] I have read the [**CONTRIBUTING**](CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the [documentation](https://plugins.jetbrains.com/docs/intellij/tools-gradle-grammar-kit-plugin.html).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by hfhbd** [comment]
@hsz Any feedback/eta?

**Comment by hsz** [comment]
Sorry for the delay — it's merged. Thank you very much, Philip!

**Comment by hfhbd** [comment]
I noticed a small bug, will create another PR: `named` requires the `java` plugin.

**Comment by hfhbd** [comment]
BTW do you accept breaking changes?

**Pull request merged**
